project_id = "eusbnxszzdtwgiblibhz"

[functions.gsm-gateway]
verify_jwt = false

[functions.manage-users]
verify_jwt = false

[functions.verify-pix]
verify_jwt = false

[functions.efi-pix]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.process-payment]
verify_jwt = false

[functions.payment-webhook]
verify_jwt = false
